### ISSUE TITLE
Error: 当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面

### ISSUE THREAD

**Issue by Caviar-X** [lz1998/ricq#86]
os info: archlinux docker
stderr :
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: 不能解析的登录响应: 235, {1288: b"\x01\0\0\x03\xe8\0\x1b\x02\0\0\0\x10 \x03\xca2\x08\x10\0\0\0\xeb\0\0\0\0\x0c\\\x17\xb7\0\0\0\xeb"}, "当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面"', src/main.rs:30:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
device: MACOS,IPAD,ANDROID_PHONE均已经尝试
源码：https://github.com/Caviar-X/qq_bot

**Comment by lz1998** [comment]
> os info: archlinux docker stderr :
> 
> ```
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: 不能解析的登录响应: 235, {1288: b"\x01\0\0\x03\xe8\0\x1b\x02\0\0\0\x10 \x03\xca2\x08\x10\0\0\0\xeb\0\0\0\0\x0c\\\x17\xb7\0\0\0\xeb"}, "当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面"', src/main.rs:30:10
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> device: MACOS,IPAD,ANDROID_PHONE均已经尝试 源码：https://github.com/Caviar-X/qq_bot

可以试试看macos的扫码登录

**Comment by LovesAsuna** [comment]
这个问题还不修一下吗

**Comment by lz1998** [comment]
> 这个问题还不修一下吗

缺 tlv 544，计算比较复杂
